// user 인증
export const AUTH_USER = 'AUTH_USER'
export const UNAUTH_USER = 'UNAUTH_USER'
export const AUTH_ERROR = 'AUTH_ERROR'
export const STATUS_ON_LIGIN = 'STATUS_ON_LIGIN'



// For Cart
export const ADD_TO_CART = 'ADD_TO_CART'
export const SELECTED_GOODS = 'SELECTED_GOODS'
export const DELETE_GOODS = 'DELETE_GOODS'


export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'


// Fetch Goods
export const START_BOOKS_FETCH = 'START_BOOKS_FETCH'
export const COMPLETE_BOOKS_FETCH = 'COMPLETE_BOOKS_FETCH'
